<a href="https://colab.research.google.com/github/not-lain/torchquantum/blob/huggingface/examples/huggingface/share_models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install -q git+https://github.com/mit-han-lab/torchquantum.git

  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.9/86.9 kB 3.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.1/82.1 kB 5.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 162.6/162.6 kB 8.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.6/48.6 MB 11.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 85.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.3/12.3 MB 90.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 324.1/324.1 kB 38.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.8/56.8 kB 7.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.1/82.1 kB 11.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.8/79.8 

# ModelHubMixin Application

In [ ]:
# login with your writing token
# token can be found here https://huggingface.co/settings/tokens
from huggingface_hub import notebook_login
notebook_login()

In [ ]:
import torch.nn as nn
import torch.nn.functional as F
import torchquantum as tq
import torchquantum.functional as tqf
from huggingface_hub import PyTorchModelHubMixin

class QFCModel(nn.Module,
               PyTorchModelHubMixin,
               tags=["torchquantum"]):

  def __init__(self, n_wires ):
    super().__init__()

    self.n_wires = n_wires # an init parameter

    self.measure = tq.MeasureAll(tq.PauliZ)

    self.encoder_gates = [tqf.rx] * 4 + [tqf.ry] * 4 + \
                         [tqf.rz] * 4 + [tqf.rx] * 4
    self.rx0 = tq.RX(has_params=True, trainable=True)
    self.ry0 = tq.RY(has_params=True, trainable=True)
    self.rz0 = tq.RZ(has_params=True, trainable=True)
    self.crx0 = tq.CRX(has_params=True, trainable=True)

  def forward(self, x):
    bsz = x.shape[0]
    # down-sample the image
    x = F.avg_pool2d(x, 6).view(bsz, 16)

    # create a quantum device to run the gates
    qdev = tq.QuantumDevice(n_wires=self.n_wires, bsz=bsz, device=x.device)

    # encode the classical image to quantum domain
    for k, gate in enumerate(self.encoder_gates):
      gate(qdev, wires=k % self.n_wires, params=x[:, k])

    # add some trainable gates (need to instantiate ahead of time)
    self.rx0(qdev, wires=0)
    self.ry0(qdev, wires=1)
    self.rz0(qdev, wires=3)
    self.crx0(qdev, wires=[0, 2])

    # add some more non-parameterized gates (add on-the-fly)
    qdev.h(wires=3)
    qdev.sx(wires=2)
    qdev.cnot(wires=[3, 0])
    qdev.qubitunitary(wires=[1, 2], params=[[1, 0, 0, 0],
                                            [0, 1, 0, 0],
                                            [0, 0, 0, 1j],
                                            [0, 0, -1j, 0]])

    # perform measurement to get expectations (back to classical domain)
    x = self.measure(qdev).reshape(bsz, 2, 2)

    # classification
    x = x.sum(-1).squeeze()
    x = F.log_softmax(x, dim=1)

    return x

model = QFCModel(n_wires = 4)

In [ ]:
model

QFCModel(
  (measure): MeasureAll()
  (rx0):  class: RX 
   parameters: Parameter containing:
  tensor([[-0.7394]], requires_grad=True) 
   wires: None 
   inverse: False
  (ry0):  class: RY 
   parameters: Parameter containing:
  tensor([[-2.3291]], requires_grad=True) 
   wires: None 
   inverse: False
  (rz0):  class: RZ 
   parameters: Parameter containing:
  tensor([[-2.2905]], requires_grad=True) 
   wires: None 
   inverse: False
  (crx0):  class: CRX 
   parameters: Parameter containing:
  tensor([[0.6369]], requires_grad=True) 
   wires: None 
   inverse: False
)

In [ ]:
model.state_dict()

OrderedDict([('rx0.params', tensor([[-0.7394]])),
             ('ry0.params', tensor([[-2.3291]])),
             ('rz0.params', tensor([[-2.2905]])),
             ('crx0.params', tensor([[0.6369]]))])

In [ ]:
# or you can use model.sav_pretrained("path") to save the model locally
model.push_to_hub("qfc-model")

model.safetensors:   0%|          | 0.00/288 [00:00<?, ?B/s]

CommitInfo(commit_url='https://huggingface.co/not-lain/qfc-model/commit/c9ff191c3506ac488ec42b75584119dfaab5a250', commit_message='Push model using huggingface_hub.', commit_description='', oid='c9ff191c3506ac488ec42b75584119dfaab5a250', pr_url=None, pr_revision=None, pr_num=None)

In [ ]:
# my model can be found here https://huggingface.co/not-lain/qfc-model

In [ ]:
# use the raw class to load the model
# no need to reinitialize the model or manually load the weights
# from pretrained can also be used to load a local model
new_model = QFCModel.from_pretrained("not-lain/qfc-model")

config.json:   0%|          | 0.00/18.0 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/288 [00:00<?, ?B/s]

In [ ]:
new_model

QFCModel(
  (measure): MeasureAll()
  (rx0):  class: RX 
   parameters: Parameter containing:
  tensor([[-0.7394]], requires_grad=True) 
   wires: None 
   inverse: False
  (ry0):  class: RY 
   parameters: Parameter containing:
  tensor([[-2.3291]], requires_grad=True) 
   wires: None 
   inverse: False
  (rz0):  class: RZ 
   parameters: Parameter containing:
  tensor([[-2.2905]], requires_grad=True) 
   wires: None 
   inverse: False
  (crx0):  class: CRX 
   parameters: Parameter containing:
  tensor([[0.6369]], requires_grad=True) 
   wires: None 
   inverse: False
)

In [ ]:
new_model.state_dict()

OrderedDict([('rx0.params', tensor([[-0.7394]])),
             ('ry0.params', tensor([[-2.3291]])),
             ('rz0.params', tensor([[-2.2905]])),
             ('crx0.params', tensor([[0.6369]]))])

In [ ]:
# same exact weights
new_model.state_dict() == model.state_dict()

True